#spring.data.mongodb.host=db
spring.data.mongodb.uri=mongodb://localhost:27017/dss
# If security is enabled for MongoDB, will need to specify the username and password:
# spring.data.mongodb.username=
# spring.data.mongodb.password=

# disabled security for testing (SHOULD BE false IN PRODUCTION)
app.security.disable=true

# Simulation configuration properties:
simulation.schedulerThreadPoolSize=10
simulation.workerThreadPoolSize=10
simulation.multipaxosPrepareTimeoutMillis=5000
simulation.multipaxosQuorum=0
simulation.heartbeatIntervalMillis=1000