#spring.data.mongodb.host=db
spring.data.mongodb.uri=mongodb://localhost:27017/dss
# If security is enabled for MongoDB, will need to specify the username and password:
# spring.data.mongodb.username=
# spring.data.mongodb.password=
